version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: escuela_nieve_db
    environment:
      MYSQL_USER : root
      MYSQL_PASSWORD : rootpassword
      MYSQL_DB : EscuelaNieve
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:


