version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: escuela_nieve_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: escuela_nieve
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./SQL:/docker-entrypoint-initdb.d

  flask_app:
    build: .
    container_name: escuela_nieve_flask
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    depends_on:
      - mysql
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0

volumes:
  mysql_data:



